name: "Exercício 2"

on: push
  
jobs:
  gerenciar_artefato:
    name: "Gerenciar Artefato"
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3.3.0
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: repositorio_tony
          path: .
          retention-days: 15
