name: "Hello world workflow"

on:
  workflow_dispatch:
  
jobs:
  print_ubuntu:
    name: Hello Ubuntu!
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello Ubuntu!
        run: |
          echo 'Data Ubuntu:'
          date
        
  print_windows:
    name: Hello Windows
    runs-on: windows-latest
    
    steps:
      - name: Hello Windows!
        run: |
          echo 'Data Windows:'
          date
        
  print_macos:
    name: Hello MacOs
    runs-on: macos-latest
    
    steps:
      - name: Hello MacOS!
        run: |
          echo 'Data MacOS:'
          date
        
  print_final:
    name: Finalizado
    runs-on: ubuntu-latest
    needs: [print_ubuntu, print_windows, print_macos]
    
    steps:
      - name: Finalizado!
        run: echo 'Finalizado as mensagens!'
